### ISSUE TITLE
Radius to the TextTagItem

### ISSUE THREAD

**Issue by truedem** [magic-goop/tag-sphere#3]
While the result look excellent - it could be used to visualize data with weight / radius option added to individual TextTagItem's.

**Comment by magic-goop** [comment]
Not sure what do you mean by radius option. Could you please provide pull request or example of what you are looking for?

**Comment by truedem** [comment]
Individual size of for each item via XML parameter - like app:iconScale="1.1"

Different / individual range from the center of the globe to for each item via parameter.

Individual colored stroke or background for each item (is this already presented? I'm not sure)

These would add an immense value for data visualization. Like

`TextTagItem(text` = "Some text $it", colorResId = R.color.green, scale = 1.1f, range = 0.7f)`

**Comment by magic-goop** [comment]
I guess, what you are requesting, could be achieved by creating custom TagItem, like in a example [here](https://github.com/magic-goop/tag-sphere/blob/master/example/src/main/java/com/magicgoop/tagpshere/example/showcase3/VectorDrawableTagItem.kt)
You can override  `drawSelf` method to do all required actions over "tag".

**Comment by truedem** [comment]
Thanks for the tip! I just thought you might be interesting in adding (huge) value to the library which is more like a toy now.
