### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by EdwinSmartBoy** [magic-goop/tag-sphere#6]
I want to implement an item that contains remote avatar, can you help me？Thanks！！

**Comment by magic-goop** [comment]
Hello!

You can use any image loading library to download avatars and add them as Drawable, for example [VectorDrawableTagItem](https://github.com/magic-goop/tag-sphere/blob/master/example/src/main/java/com/magicgoop/tagpshere/example/showcase3/VectorDrawableTagItem.kt) from Showcase3 of the example project.

Here is a rough implementation using [coil library](https://github.com/coil-kt/coil):
``` Kotlin
private val avatars = listOf(
            "https://...",
            "https://...",
        )
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
     super.onViewCreated(view, savedInstanceState)
     // some initialization
    ...

    scope.launch {
            withContext(Dispatchers.IO) {
                avatars.forEach { url ->
                    val request = ImageRequest.Builder(context)
                        .data(url)
                        .build()
                    imageLoader.execute(request).drawable?.let { d ->
                        withContext(Dispatchers.Main) {
                            tagSphereView.addTag(VectorDrawableTagItem(d))
                        }
                    }
                }
            }
        }
```

And result can look smth like this:

https://github.com/magic-goop/tag-sphere/assets/18048964/9cc8c409-3ab8-4d5c-a3ed-103e1c15e698

**Comment by EdwinSmartBoy** [comment]
Thanks, this worked great for me
