### ISSUE TITLE
auto rotation speed

### ISSUE THREAD

**Issue by EdwinSmartBoy** [magic-goop/tag-sphere#7]
Hi, The rate of automatic scrolling cannot be set externally，Is it possible to add a method for external settings，Thanks!!

**Comment by AleksRychkov** [comment]
Hello!

Have you tried to change values passed to the `startAutoRotation` function?

**Comment by EdwinSmartBoy** [comment]
Unable to set scroll data for sphere
![image](https://github.com/magic-goop/tag-sphere/assets/17477816/98acabdb-0bfa-48f8-a544-087b4eb8234d)

**Comment by AleksRychkov** [comment]
You can fork repository and make any required adjustments. At the moment, I am unable to make any changes.
